# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
if Rails.env.development?
  AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
  user = User.create!(email: 'user@example.com',
    nickname: 'user',
    favourite_color: 'yellow',
    password: 'password',
    password_confirmation: 'password'
  )
  user.confirm
  5.times do |i|
    todolist = user.todolists.create!(name: "Todolist no #{i}")
    12.times do |j|
      todolist.tasks.create!(title: "Task no #{j}",
                             description: 'This is example task generated by seed',
                             deadline: rand(1.month).seconds.ago
                            )
    end
  end
end
